dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: beta

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless

env:
  - CHROME_BIN=google-chrome-beta
  
# deploy:
#   skip_cleanup: true
#   provider: firebase
#   token:
#     secure: ""  