dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  chrome: beta

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless